DROP DATABASE IF EXISTS bus_schedule;
CREATE DATABASE bus_schedule;
USE bus_schedule;

-- Location --

 CREATE TABLE Location
(
 LocationId INT NOT NULL AUTO_INCREMENT,
 Name VARCHAR(160) NOT NULL,
 CONSTRAINT PK_City PRIMARY KEY (LocationId)
);

CREATE TABLE Station
(
 StationId INT NOT NULL AUTO_INCREMENT,
 Name VARCHAR(160) NOT NULL,
 Street VARCHAR(160) NOT NULL,
 NumberStreet VARCHAR(160) NOT NULL,
 LocationId INT NOT NULL,
 CONSTRAINT PK_Station PRIMARY KEY (StationId)
);

-- Schedule And Route -- 
CREATE TABLE Route
(
RouteId INT NOT NULL AUTO_INCREMENT,
BusId INT NOT NULL,
Name VARCHAR(160) NOT NULL,
DepartureStation INT NOT NULL,
ArrivalStation INT NOT NULL,
DepartureTime TIME NOT NULL,
ArrivalTime TIME NOT NULL,
CONSTRAINT UQ_Route_Name UNIQUE (Name),
CONSTRAINT PK_Route PRIMARY KEY (RouteId)
);

CREATE TABLE Schedule
(
ScheduleId INT NOT NULL AUTO_INCREMENT,
RouteId INT NOT NULL,
StationId INT NOT NULL,
OrderRoute INT NOT NULL,
DepartureTime TIME,
ArrivalTime TIME,
CONSTRAINT PK_Schedule PRIMARY KEY (ScheduleId)
);

-- Bus details -- 

CREATE TABLE Bus
(
BusId INT NOT NULL AUTO_INCREMENT,
Model VARCHAR(28) NOT NULL,
BusNumber VARCHAR(28) NOT NULL,
Seats  INT NOT NULL,
CONSTRAINT UQ_Bus_BusNumber UNIQUE (BusNumber),
CONSTRAINT PK_Bus PRIMARY KEY (BusId)
);

    -- Tickets -- 
CREATE TABLE Ticket
(
TicketId INT NOT NULL AUTO_INCREMENT,
UserId INT NOT NULL,
RouteId INT NOT NULL,
SalesTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ScheduleDepartureStationId INT NOT NULL,
ScheduleArrivalStationId INT NOT NULL,
Price NUMERIC(10,2) NOT NULL,
TripDate DATE NOT NULL,
CONSTRAINT PK_Ticket PRIMARY KEY (TicketId)
);

CREATE TABLE User
(
UserId INT NOT NULL AUTO_INCREMENT,
FirstName VARCHAR(255) NOT NULL,
LastName VARCHAR(255) NOT NULL,
Email VARCHAR(255),
Password VARCHAR(255),
RoleType VARCHAR(255)  NOT NULL,
CONSTRAINT PK_User PRIMARY KEY (UserId)
);


ALTER TABLE Station ADD CONSTRAINT FK_StationLocationId
FOREIGN KEY (LocationId) REFERENCES Location (LocationId) ON  DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Route ADD CONSTRAINT FK_RouteArrivalStation
FOREIGN KEY (ArrivalStation) REFERENCES Station (StationId) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE Route ADD CONSTRAINT FK_RouteDepartureStation
FOREIGN KEY (DepartureStation) REFERENCES Station (StationId) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE Route ADD CONSTRAINT FK_RouteBusId
FOREIGN KEY (BusId) REFERENCES Bus (BusId) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE Schedule ADD CONSTRAINT FK_ScheduleStationId
FOREIGN KEY (StationId) REFERENCES Station (StationId) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE Schedule ADD CONSTRAINT FK_ScheduleRouteId
FOREIGN KEY (RouteId) REFERENCES Route (RouteId) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE Ticket ADD CONSTRAINT FK_TicketUserId
FOREIGN KEY (UserId) REFERENCES User (UserId) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE Ticket ADD CONSTRAINT FK_TicketScheduleArrivalStationId
FOREIGN KEY (ScheduleArrivalStationId) REFERENCES Schedule (ScheduleId) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE Ticket ADD CONSTRAINT FK_TicketScheduleDepartureStationId
FOREIGN KEY (ScheduleDepartureStationId) REFERENCES Schedule (ScheduleId) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE Ticket ADD CONSTRAINT FK_TicketRouteId
FOREIGN KEY (RouteId) REFERENCES Route (RouteId) ON DELETE NO ACTION ON UPDATE NO ACTION;

